### ISSUE TITLE
Error when format disk

### ISSUE THREAD

**Issue by chuc2rk** [mndti/virtual-dsm-openwrt-qemu#1]
I get erro when start install, please help
![image](https://github.com/mndti/virtual-dsm-openwrt-qemu/assets/10666019/72cc8874-dcdf-4abe-baeb-d400a5fdbe34)

> root@HHV:~# nano dsm.sh
root@HHV:~# sh dsm.sh
[!] Enter script language / Insira o idioma do script
default/padrao [en] (en/pt): en
[!] Do you want to continue?
default/padrao [n] (y/n): y
[!] Enter the version to virtual dsm (7/6)
default/padrao [7]:
[!] Enter the name to virtual dsm (a-z0-9_-)
default/padrao [virtual-dsm]:
[!] Do you want to define the mac/model/serial?
default/padrao [n] (y/n):
[!] Enter the path to virtual dsm
default/padrao [/mnt/virtual-dsm]:
Creating folders...
Downloading release/7.0.1/42218/DSM_VirtualDSM_42218.pat, please wait...
Downloading 'https://global.synologydownload.com/download/DSM/release/7.0.1/42218/DSM_VirtualDSM_42218.pat'
Connecting to 104.22.0.171:443
Writing to '/mnt/virtual-dsm/tmp/vdsm_temp.pat'
/mnt/virtual-dsm/tmp 100% |*******************************|   362M  0:00:00 ETA
Download completed (379637760 bytes)
Preparing synoboot.qcow2 file...
Downloading https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/22.03.5/packages/x86_64/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://downloads.openwrt.org/releases/22.03.5/packages/x86_64/base/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/22.03.5/packages/x86_64/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://downloads.openwrt.org/releases/22.03.5/packages/x86_64/luci/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/22.03.5/packages/x86_64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://downloads.openwrt.org/releases/22.03.5/packages/x86_64/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/22.03.5/packages/x86_64/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://downloads.openwrt.org/releases/22.03.5/packages/x86_64/routing/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/22.03.5/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading https://downloads.openwrt.org/releases/22.03.5/packages/x86_64/telephony/Packages.sig
Signature check passed.
opkg install unzip...
Installing unzip (6.0-8) to root...
Downloading https://downloads.openwrt.org/releases/22.03.5/packages/x86_64/packages/unzip_6.0-8_x86_64.ipk
Configuring unzip.
opkg install qemu-img...
Installing qemu-img (6.2.0-2) to root...
Downloading https://downloads.openwrt.org/releases/22.03.5/packages/x86_64/packages/qemu-img_6.2.0-2_x86_64.ipk
Configuring qemu-img.
Extract synoboot...
Move synoboot to permanent directory...
Download vdsm_temp.cfg...
Downloading 'https://raw.githubusercontent.com/mndti/virtual-dsm-openwrt-qemu/main/vdsm_temp.cfg'
Connecting to 185.199.109.133:443
Writing to '/mnt/virtual-dsm/tmp/vdsm_temp.cfg'
/mnt/virtual-dsm/tmp 100% |*******************************|   644   0:00:00 ETA
Download completed (644 bytes)
Save port 12346 to cfg...
Save synoboot.qcow2 to cfg...
Create synosystem.qcow2 with size of 12GB...
Formatting '/mnt/virtual-dsm/synosystem.qcow2', fmt=qcow2 cluster_size=65536 extended_l2=off compression_type=zlib size=12884901888 lazy_refcounts=off refcount_bits=16
Save synosystem.qcow2 to cfg...
[!] Enter the path to synodisk1
default/padrao [/mnt/virtual-dsm]:
[!] Enter synodisk1 size
default/padrao [6G]: 16
Create synodisk1 with 16...
Formatting '/mnt/virtual-dsm/synodisk1.qcow2', fmt=qcow2 cluster_size=65536 extended_l2=off compression_type=zlib size=16 lazy_refcounts=off refcount_bits=16
Save synodisk1.qcow2 to cfg...
[!] Do you want add synodisk2?
default/padrao [n] (y/n):
[!] Enter name of the bridge interface net0
default/padrao [br-lan]:
Save net0 to cfg...
[!] Do you want add another lan?
default/padrao [n] (y/n):
[!] Enter the number of processor cores, only numbers (example: 1/2/4)
default/padrao [2]:
[!] Enter the amount of ram memory, only numbers (example: 1048/2048/4096)
default/padrao [1024]:
Save cores/memory to cfg...
Copy vdsm_temp.sh to /mnt/virtual-dsm...
Download vdsm_temp.sh...
Downloading 'https://raw.githubusercontent.com/mndti/virtual-dsm-openwrt-qemu/main/vdsm_temp.sh'
Connecting to 185.199.109.133:443
Writing to '/mnt/virtual-dsm/tmp/vdsm_temp.sh'
/mnt/virtual-dsm/tmp 100% |*******************************|  2345   0:00:00 ETA
Download completed (2345 bytes)
Update vdsm_temp.sh script...
Copy vdsm_temp.sh script to init.d folder...
opkg install curl ...
Installing curl (8.6.0-1) to root...
Downloading https://downloads.openwrt.org/releases/22.03.5/packages/x86_64/packages/curl_8.6.0-1_x86_64.ipk
Installing libmbedtls12 (2.28.7-1) to root...
Downloading https://downloads.openwrt.org/releases/22.03.5/packages/x86_64/base/libmbedtls12_2.28.7-1_x86_64.ipk
Installing libnghttp2-14 (1.44.0-1) to root...
Downloading https://downloads.openwrt.org/releases/22.03.5/packages/x86_64/packages/libnghttp2-14_1.44.0-1_x86_64.ipk
Installing libcurl4 (8.6.0-1) to root...
Downloading https://downloads.openwrt.org/releases/22.03.5/packages/x86_64/packages/libcurl4_8.6.0-1_x86_64.ipk
Configuring libmbedtls12.
Configuring libnghttp2-14.
Configuring libcurl4.
Configuring curl.
opkg install kmod-tun qemu-bridge-helper qemu-x86_64-softmmu ...
Package kmod-tun (5.10.176-1) installed in root is up to date.
Package qemu-bridge-helper (6.2.0-2) installed in root is up to date.
Package qemu-x86_64-softmmu (6.2.0-2) installed in root is up to date.
opkg install kmod-kvm-intel intel-microcode iucode-tool ...
Package kmod-kvm-intel (5.10.176-1) installed in root is up to date.
Installing intel-microcode (20220809-1) to root...
Downloading https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/packages/intel-microcode_20220809-1_x86_64.ipk
Installing iucode-tool (2.3.1-2) to root...
Downloading https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/packages/iucode-tool_2.3.1-2_x86_64.ipk
Configuring intel-microcode.
Configuring iucode-tool.
Download host.bin to /mnt/virtual-dsm...
Downloading 'https://github.com/mndti/virtual-dsm-openwrt-qemu/raw/main/host.bin'
Connecting to 20.205.243.166:443
Redirected to /mndti/virtual-dsm-openwrt-qemu/main/host.bin on raw.githubusercontent.com
Writing to '/mnt/virtual-dsm/host.bin'
/mnt/virtual-dsm/hos 100% |*******************************|  6794k  0:00:00 ETA
Download completed (6957520 bytes)
Delete temp folder and files...
/etc/init.d/virtual-dsm enable
/etc/init.d/virtual-dsm start
Start Virtual DSM...please wait...
sh: 6: unknown operand
Access the link below to complete the installation of Virtual DSM...
[!] http://10.3.1.41:5000
root@HHV:~# block info
block: Usage: block <info|mount|umount|detect>
root@HHV:~# block info
/dev/sda1: UUID="1234-ABCD" LABEL="kernel" VERSION="FAT16" MOUNT="/boot" TYPE="vfat"
/dev/sda2: UUID="ff313567-e9f1-5a5d-9895-3ba130b4a864" LABEL="rootfs" VERSION="1.0" MOUNT="/" TYPE="ext4"
root@HHV:~# opkg install block-mount
Package block-mount (2022-06-02-93369be0-2) installed in root is up to date.

**Comment by mndti** [comment]
@chuc2rk I believe the problem is the size of the disk, please repeat the installation, putting 16G instead of 16 on synodisk1

![image](https://github.com/mndti/virtual-dsm-openwrt-qemu/assets/29640930/ac40e64a-c832-4a40-9bc3-b29f676f2a89)

Before doing so:
```
rm -r /mnt/virtual-dsm
rm /etc/init.d/virtual-dsm
```

You can also try:
```
/etc/init.d/virtual-dsm stop
rm /mnt/virtual-dsm/synodisk1.qcow2
qemu-img create -f qcow2 /mnt/virtual-dsm/synodisk1.qcow2 16G
/etc/init.d/virtual-dsm start
```

Access: http://10.3.1.41:5000/

**Comment by chuc2rk** [comment]
Thank you so much your quick reply. Work great now!
